[package]
name = "drift-abi-gen"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "drift-abi-gen"
path = "src/main.rs"

[dependencies]
proc-macro2 = "*"
quote = "*"
syn = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
sha2 = "*"