[package]
name = "event-subscriber"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
drift-rs = { path = "../../../drift-rs" }
env_logger = "0.11"
futures-util = "0.3.31"
solana-sdk = "2"
tokio = "*"
clap = { version = "4.4.8", features = ["derive"] }
