# Workflow to trigger manual update e.g incase of failed/missed workflow
name: "Trigger IDL update"
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'IDL version (e.g. 2.111.0)'
        required: true
        type: string

jobs:
  trigger-dispatch:
    runs-on: ubicloud
    steps:
    - name: trigger dispatch event
      run: |
        curl -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: token ${{ secrets.GH_PAT }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/drift-labs/drift-rs/dispatches \
        -d '{"event_type":"sdk-update","client_payload":{"version":"${{ github.event.inputs.version }}"}}'
