name: "Bump libdrift"
on:
  repository_dispatch:
    types: ['libdrift-update']

jobs:
  update-libdrift-submodule:
    permissions:
      contents: write
    runs-on: ubicloud
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
      
      - name: Update submodule
        run: |
          cd crates/drift-ffi-sys
          git checkout master
          git pull origin master
          cd ../..
          git add -u

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if git diff --staged --quiet; then
            echo "No changes to submodule, skipping commit"
            exit 0
          fi

          git commit -m "chore: bump drift-ffi-sys to latest version 🤖"
          git push origin main -f
